name: nlp-clustering-prototype
channels:
  - defaults
dependencies:
  - python>=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - pip
  - pip:
      - sentence-transformers
      - transformers
      - langdetect